services:
  sonarr:
    image: sonarr/sonarr:4.0.19.2979
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    ports:
      - 8989:8989
      
    volumes:
      - /nfs/share/data/sonarr/config:/config
      - /nfs/share/data:/data

    restart: unless-stopped