services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.2.2_v2.0.13-ls464
    container_name: qbittorrent
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - WEBUI_PORT=8081
      - TZ=Europe/Lisbon
    volumes:
      - /opt/qbittorrent/config:/config
      - /nfs/share/data/qbittorrent/torrents:/torrents
      - /nfs/share/data/downloads:/data/downloads
      - /nfs/share:/share
    network_mode: container:wireguard
    restart: unless-stopped