services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
   # network_mode: bridge
#    ports:
#      - 13378:80
    volumes:
      - /nfs/share/data/audiobookshelf/audiobooks:/audiobooks
      - /nfs/share/data/audiobookshelf/podcasts:/podcasts
      - /nfs/share/data/audiobookshelf/config:/config
      - /nfs/share/data/audiobookshelf/metadata:/metadata
    environment:
      - TZ=Europe/Lisbon
      - PUID=1000
      - PGID=1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.audiobookshelf.rule=Host(`audiobooks.gonsa.org`)"
      - "traefik.http.routers.audiobookshelf.entrypoints=https"
      - "traefik.http.routers.audiobookshelf.tls=true"
      - "traefik.http.routers.audiobookshelf.tls.certresolver=cloudflare"
    # HTTP-to-HTTPS redirect
      - "traefik.http.routers.audiobookshelf-http.entrypoints=http"
      - "traefik.http.routers.audiobookshelf-http.rule=Host(`audiobooks.gonsa.org`)"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.audiobookshelf-http.middlewares=redirect-to-https"
      - "traefik.http.routers.audiobookshelf.middlewares=secured@file"
      - "traefik.http.services.audiobookshelf.loadbalancer.server.port=80"
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true