services:
  bentopdf:
    image: bentopdfteam/bentopdf:v2.8.8
    container_name: bentopdf
#    ports:
#      - '3008:8080'
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # Local only (no auth)
      - "traefik.http.routers.bentopdf-home.rule=Host(`bentopdf.home.gonsa.org`)"
      - "traefik.http.routers.bentopdf-home.entrypoints=https"
      - "traefik.http.routers.bentopdf-home.tls.certresolver=cloudflare"

      # OpenWebUI - External (with auth)
      - "traefik.http.routers.bentopdf.rule=Host(`bentopdf.gonsa.org`)"
      - "traefik.http.routers.bentopdf.entrypoints=https"
      - "traefik.http.routers.bentopdf.tls.certresolver=cloudflare"
      - "traefik.http.routers.bentopdf.middlewares=authentik@file"

      # HTTP redirects for both domains
      - "traefik.http.routers.bentopdf-http.entrypoints=http"
      - "traefik.http.routers.bentopdf-http.rule=Host(`bentopdf.gonsa.org`)"
      - "traefik.http.routers.bentopdf-http.middlewares=redirect-to-https"

      # Shared middleware and service
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.services.bentopdf.loadbalancer.server.port=8080"
    networks:
      - traefik-net
networks:
  traefik-net:
    external: true
