services:
  prometheus:
    image: prom/prometheus:3.14.0
    container_name: prometheus
    user: "1000:1000"
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=15d
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    volumes:
      - /nfs/share/data/prometheus:/prometheus
      - /nfs/share/data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true