services:
  immich-kiosk:
    image: ghcr.io/damongolding/immich-kiosk:v0.43.1
    container_name: immich-kiosk
    network_mode: bridge
    environment:
      TZ: "Europe/Lisbon"
      # Required settings
      KIOSK_IMMICH_API_KEY: ${KIOSK_IMMICH_API_KEY}
      KIOSK_IMMICH_URL: ${KIOSK_IMMICH_URL}
      # Clock
      KIOSK_SHOW_TIME: TRUE
      KIOSK_TIME_FORMAT: 24
      KIOSK_SHOW_DATE: TRUE
      KIOSK_DATE_FORMAT: DDDD DD MMMM YYYY
      # Kiosk behaviour
      KIOSK_REFRESH: 10
      KIOSK_DISABLE_SCREENSAVER: FALSE
      # Asset sources
      KIOSK_SHOW_ARCHIVED: FALSE
      KIOSK_ALBUM: ${KIOSK_ALBUM}
      KIOSK_PERSON: ${KIOSK_PERSON}
      # UI
      KIOSK_DISABLE_UI: FALSE
      KIOSK_HIDE_CURSOR: FALSE
      KIOSK_FONT_SIZE: 100
      KIOSK_BACKGROUND_BLUR: TRUE
      KIOSK_THEME: FADE
      KIOSK_LAYOUT: single
      # Sleep mode
      KIOSK_SLEEP_START: 22
      KIOSK_SLEEP_END: 7
      # Transistion options
      KIOSK_TRANSITION: NONE
      KIOSK_FADE_TRANSITION_DURATION: 1
      KIOSK_CROSS_FADE_TRANSITION_DURATION: 1
      # Image display settings
      KIOSK_SHOW_PROGRESS: FALSE
      KIOSK_IMAGE_FIT: CONTAIN
      KIOSK_IMAGE_ZOOM: FALSE
      KIOSK_IMAGE_ZOOM_AMOUNT: 120
      # Image metadata
      KIOSK_SHOW_IMAGE_TIME: TRUE
      KIOSK_IMAGE_TIME_FORMAT: 24
      KIOSK_SHOW_IMAGE_DATE: TRUE
      KIOSK_IMAGE_DATE_FORMAT: DD-MM-YYYY
      KIOSK_SHOW_IMAGE_EXIF: TRUE
      KIOSK_SHOW_IMAGE_LOCATION: FALSE
      KIOSK_SHOW_IMAGE_ID: FALSE
      # Kiosk settings
      KIOSK_WATCH_CONFIG: FALSE
      KIOSK_PASSWORD: ""
      KIOSK_CACHE: TRUE
      KIOSK_PREFETCH: TRUE
      KIOSK_ASSET_WEIGHTING: TRUE
      KIOSK_PORT: 3005
    ports:
      - 3005:3005
    #restart: on-failure