services:
  anchor:
    image: ghcr.io/zhfahim/anchor:0.17.1
    container_name: anchor
    restart: unless-stopped

    environment:
      APP_URL: ${APP_URL}

    volumes:
      - /nfs/share/data/anchor:/data

    networks:
      - traefik-net

    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik-net'

      # Service
      - 'traefik.http.services.anchor.loadbalancer.server.port=3000'

      # Local
      - 'traefik.http.routers.anchor-home.rule=Host(`anchor.home.gonsa.org`)'
      - 'traefik.http.routers.anchor-home.entrypoints=https'
      - 'traefik.http.routers.anchor-home.tls=true'
      - 'traefik.http.routers.anchor-home.tls.certresolver=cloudflare'
      - 'traefik.http.routers.anchor-home.service=anchor'

      # External
      - 'traefik.http.routers.anchor.rule=Host(`anchor.gonsa.org`)'
      - 'traefik.http.routers.anchor.entrypoints=https'
      - 'traefik.http.routers.anchor.tls=true'
      - 'traefik.http.routers.anchor.tls.certresolver=cloudflare'
      - 'traefik.http.routers.anchor.service=anchor'

      # HTTP -> HTTPS
      - 'traefik.http.routers.anchor-http.rule=Host(`anchor.gonsa.org`) || Host(`anchor.home.gonsa.org`)'
      - 'traefik.http.routers.anchor-http.entrypoints=http'
      - 'traefik.http.routers.anchor-http.middlewares=redirect-to-https'

networks:
  traefik-net:
    external: true