services:
  slskd:
    image: slskd/slskd
    network_mode: bridge
    container_name: slskd
    ports:
      - "5030:5030"
      - "5031:5031"
      - "50300:50300"
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - /nfs/share/data/slskd:/app
      - /nfs/share/data/slskd:/downloads
      - /nfs/share/data/slskd:/incomplete
      - /nfs/share/mp3:/music