services:
  foxy:
    image: lscr.io/linuxserver/firefox:1155.0build1-1xtradeb2.2404.1-ls119
    container_name: foxy

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon

      # Clipboard
      - SELKIES_CLIPBOARD_ENABLED=true
      - SELKIES_CLIPBOARD_IN_ENABLED=true
      - SELKIES_CLIPBOARD_OUT_ENABLED=true

      #Credentials
      - CUSTOM_USER=${FIREFOX_USER}
      - PASSWORD=${FIREFOX_PASSWORD}

      # Optional: don't need the clipboard sidebar
      - SELKIES_UI_SIDEBAR_SHOW_CLIPBOARD=false

    volumes:
      - /nfs/share/data/foxy:/config

    mem_limit: 4g
    memswap_limit: 8g

    shm_size: "1gb"

    tmpfs:
      - /tmp:size=1g,mode=1777

    restart: unless-stopped

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.foxy.rule=Host(`foxy.gonsa.org`)"
      - "traefik.http.routers.foxy.entrypoints=https"
      - "traefik.http.routers.foxy.tls=true"
      - "traefik.http.routers.foxy.tls.certresolver=cloudflare"

      - "traefik.http.routers.foxy.middlewares=rate-limit@file,authentik@file"

      - "traefik.http.services.foxy.loadbalancer.server.port=3000"
      - "traefik.http.services.foxy.loadbalancer.server.scheme=http"

    networks:
      - traefik-net

networks:
  traefik-net:
    external: true