services:
  tautulli-manager:
    image: ghcr.io/10mfox/gethomepage-tautulli-api:sha256-22337c7d451cbb647e72c7b040ccaaf2db929417aafa8f1676d578a4b7352414.sig
    container_name: tautulli-api-manager
    environment:
      - TAUTULLI_CUSTOM_PORT=3010
      - PUID=1000   # Your user ID
      - PGID=1000   # Your group ID
    ports:
      - "3010:3010"
    volumes:
      - /nfs/share/data/gethomepage-tautulli-api/config:/app/config
    restart: unless-stopped