services:
  kometa:
    image: kometateam/kometa:v2.4.8
    container_name: kometa
    environment:
      - KOMETA_RUN=true 
      - KOMETA_TIMES=05:00
      - TZ=Europe/Lisbon
     # - KOMETA_CONFIG=/config/special-config.yml 
     # - KOMETA_OVERLAYS_ONLY=true 
     # - KOMETA_RUN_LIBRARIES=Movies 
    volumes:
      - /nfs/share/data/kometa/config:/config
     # - /nfs/share/data/umtk:/nfs/share/data/umtk
      - /nfs/share/data/tssk:/nfs/share/data/tssk