services:
  crowdsec:
    image: crowdsecurity/crowdsec:v1.8.1
    container_name: crowdsec
    environment:
      CROWDSEC_PROMETHEUS_ENABLED: true
      CROWDSEC_PROMETHEUS_LISTEN: 0.0.0.0:6060
      LAPI_PROMETHEUS_ENABLED: true
      LAPI_PROMETHEUS_LISTEN: 0.0.0.0:6061
      TZ: Europe/Lisbon
      GID: "${GID-1000}"
      COLLECTIONS: "crowdsecurity/linux crowdsecurity/traefik"
      #  Tell CrowdSec to use Postgres! 
      DB_BACKEND: pgsql
      POSTGRES_HOST: crowdsec-db
      POSTGRES_DB: crowdsec
      POSTGRES_USER: crowdsec
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      #  ------------------------------ 
    volumes:
      - /nfs/share/data/crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
      - /home/gonsa/local-crowdsec-db:/var/lib/crowdsec/data/
      - /nfs/share/data/crowdsec/config:/etc/crowdsec/
      - /home/gonsa/traefik/logs:/var/log/traefik/:ro
      - /etc/localtime:/etc/localtime:ro

    networks:
      traefik-net:

    logging:               #  capping huge logs
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  
  crowdsec-db:
    image: postgres:15-alpine
    container_name: crowdsec-db
    environment:
      POSTGRES_DB: crowdsec
      POSTGRES_USER: crowdsec
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - crowdsec-pg-data:/var/lib/postgresql/data
    networks:
      - traefik-net
    restart: unless-stopped

    security_opt:
      - no-new-privileges:true

  crowdsec-web-ui:
    image: ghcr.io/theduffman85/crowdsec-web-ui:2026.10.2
    container_name: crowdsec_web_ui

    environment:
      TZ: Europe/Lisbon

      CONFIG_INSTANCE_NAME: Home CrowdSec
      CONFIG_INSTANCE_LAPI_URL: http://crowdsec:8080
      CONFIG_INSTANCE_LAPI_AUTH_USERNAME: ${CONFIG_INSTANCE_LAPI_AUTH_USERNAME}
      CONFIG_INSTANCE_LAPI_AUTH_PASSWORD: ${CONFIG_INSTANCE_LAPI_AUTH_PASSWORD}

      CONFIG_UI_TIME_ZONE: Europe/Lisbon
      CONFIG_UI_TIME_FORMAT: 24h

    volumes:
      - /nfs/share/data/crowdsec-web-ui/data:/app/data

    expose:
      - "3000"

    networks:
      - traefik-net

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"

      - "traefik.http.routers.crowdsec-web-ui.rule=Host(`crowdsec.home.gonsa.org`)"
      - "traefik.http.routers.crowdsec-web-ui.entrypoints=https"
      - "traefik.http.routers.crowdsec-web-ui.tls=true"

      - "traefik.http.services.crowdsec-web-ui.loadbalancer.server.port=3000"

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    security_opt:
      - no-new-privileges:true

    restart: unless-stopped
    
volumes:
  crowdsec-pg-data:
networks:
  traefik-net:
    external: true